#!/bin/bash
echo Compiling packages...
yarn build:server
echo Building docker image...
docker build -t billvog/ferman:latest .
echo Pushing image to Docker Hub...
docker push billvog/ferman:latest
echo Deploy image to dokku...
ssh -i ~/.ssh/ferman-master.pem ubuntu@api.ferman.ga "sudo docker pull billvog/ferman:latest && sudo docker tag billvog/ferman:latest dokku/api:latest && dokku deploy api latest"